### ISSUE TITLE
Score past 1600

### ISSUE THREAD

**Issue by NotMoni** [WeGoToMars/WeGoToMars.github.io#4]
If you get input 2 as reading, and 0 on math and 0 on writing the confidence interval says 1580 - 1610. The max on the SAT is 1600.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/40552237/169428729-be991162-87b9-4fef-807c-13e94e640060.png">

**Comment by WeGoToMars** [comment]
Fixed in the latest [commit](https://github.com/WeGoToMars/WeGoToMars.github.io/commit/82ca3bb010a9bbef8ff8dad25ef72614589e1e93). Score range is not very necessary if you are so close to the top score.

Thanks for the report!
