### ISSUE TITLE
Plan to add May SAT ?

### ISSUE THREAD

**Issue by NotMoni** [WeGoToMars/WeGoToMars.github.io#5]
Scores out today. Any plans to add them to the curves for better predictions ?

**Comment by WeGoToMars** [comment]
Added in the latest [commit](https://github.com/WeGoToMars/WeGoToMars.github.io/commit/382e26ef21cfb43490980c96f13f2c7582abd329). 
I need to wait for a few days to make sure all the data is available on r/sat threads (even now, many data points are missing, and I have to guess).
Thanks for the reminder!
